config/routes.rb
Rails.application.routes.draw do

  root 'compressed_urls#index'
  resources :compressed_urls
  resources :blogs do
    resources :comments do
      member do
        get :like
      end
    end
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :comments

  validates_presence_of :header, :text
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog

  validates_presence_of :text

  def like!
    self.likes ||= 0
    self.likes += 1
    self.save
  end
end

app/models/compressed_url.rb
class CompressedUrl < ActiveRecord::Base

  def compress!
    self.name = SecureRandom.hex
    self.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find params[:id]
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to blogs_path
    else
      flash[:errors] = @blog.errors.messages
      redirect_to :back
    end
  end

  def update
    @blog = Blog.find params[:id]

    if @blog.update_attributes(blog_params)
      redirect_to blogs_path
    else
      flash[:errors] = @blog.errors.messages
      redirect_to :back
    end
  end

  def destroy
    @blog = Blog.find params[:id]
    @blog.destroy
    redirect_to blogs_path
  end

    private

  def blog_params
    params.require(:blog).permit(:header, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @blog = Blog.find params[:blog_id]
  end

  def edit
    @blog = Blog.find params[:blog_id]
    @comment = Comment.find params[:id]
  end

  def like
    @comment = Comment.find params[:id]
    @comment.like!
    redirect_to :back
  end

  def create
    @comment = Comment.new(comment_params.merge(blog_id: params[:blog_id]))

    if @comment.save
      redirect_to :back
    else
      flash[:errors] = @comment.errors.messages
      redirect_to :back
    end
  end

  def update
    @comment = Comment.find params[:id]

    if @comment.update_attributes(comment_params)
      redirect_to new_blog_comment_path
    else
      flash[:errors] = @comment.errors.messages
      redirect_to :back
    end
  end

  def destroy
    @comment = Comment.find params[:id]
    @comment.destroy
    redirect_to :back
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/compressed_urls_controller.rb
class CompressedUrlsController < ApplicationController
  def index
    @urls = CompressedUrl.all
  end

  def new
    @url = CompressedUrl.new
  end

  def edit
    @url = CompressedUrl.find params[:id]
  end

  def create
    @url = CompressedUrl.new(compressed_url_params)
    @url.compress!
    if @url.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @url = CompressedUrl.find params[:id]

    if @url.update_attributes!(compressed_url_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @url = CompressedUrl.find params[:id]
    @url.destroy
    redirect_to root_path
  end

  private

  def compressed_url_params
    params.require(:compressed_url).permit(:name, :origin_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  Header: <%= f.text_field :header %><br />
  Text: <%= f.text_area :text %><br />
  <%= f.submit %>
<% end %>

app/views/blogs/edit.html.erb
<h3> Edit Post </h3>
<%= render 'form' %>

<%= link_to '< Back', blogs_path %>

app/views/blogs/index.html.erb
<h2> Blog </h2>
<ul>
  <% @blogs.each do |blog| %>
    <li>
      <%= blog.header %>
      <%= link_to 'Comment', new_blog_comment_path(blog), class: 'btn btn-sm btn-success' %>
      <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-sm btn-primary' %>
      <%= link_to 'Delete', blog_path(blog), method: :delete, class: 'btn btn-sm btn-danger' %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add blog', new_blog_path %>

app/views/blogs/new.html.erb
<h3> New Post </h3>
<%= render 'form' %>

<%= link_to '< Back', blogs_path %>

app/views/comments/_form.html.erb
<%= form_for [@blog, @comment] do |f| %>
  Text: <%= f.text_area :text %><br />
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h3> Edit Post </h3>
<%= render 'form' %>

<%= link_to '< Back', new_blog_comment_path %>

app/views/comments/new.html.erb
<h3> New Comment </h3>

header: <%= @blog.header %> </br>
text: <%= @blog.text %> </br>
Comments:
</br>
<ul>
<% @blog.comments.each do |comment| %>
  <li>
    <%= comment.text %>
    <%= link_to 'Like', like_blog_comment_path(@blog, comment) %>
    <%= comment.likes %>
    <%= link_to 'Edit', edit_blog_comment_path(@blog, comment) %>
    <%= link_to 'Delete', blog_comment_path(@blog, comment), method: :delete %>
  </li>
<% end %>
</ul>
Add comment:
</br>
<%= render 'form' %>
</br>
<%= link_to '< Back', blogs_path %>

app/views/compressed_urls/_form.html.erb
<%= form_for @url do |f| %>
  <% if @url.persisted? %>
    Name: <%= f.text_field :name %><br />
  <% end %>
  Origin Url: <%= f.text_field :origin_url %><br />
  <%= f.submit %>
<% end %>

app/views/compressed_urls/edit.html.erb
<h3> Edit URL </h3>
<%= render 'form' %>

<%= link_to '< Back', root_path %>

app/views/compressed_urls/index.html.erb
<h2> Url List </h2>
<ul>
  <% @urls.each do |url| %>
    <li>
      <%= link_to url.name, url.origin_url, target: "_blank" %>
      <%= link_to 'Edit', edit_compressed_url_path(url), class: 'btn btn-sm btn-primary' %>
      <%= link_to 'Delete', compressed_url_path(url), method: :delete, class: 'btn btn-sm btn-danger' %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add Url', new_compressed_url_path %>

app/views/compressed_urls/new.html.erb
<h3> New URL </h3>
<%= render 'form' %>

<%= link_to '< Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "URL Compressor" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">URL Compressor</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "New", new_compressed_url_path  %></li>
            <li><%= link_to "List", root_path  %></li>
            <li><%= link_to "Blog", blogs_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= flash[:errors] %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>